### ISSUE TITLE
Aditya Eka Maulana/programmer

### ISSUE THREAD

**Issue by adityaemaulana** [helloproclub/takehome#3]
this is some of my project:

- https://github.com/Bombardirgh/simple-shopping-app
- https://github.com/Bombardirgh/actor-film-relation-modelling

**Comment by wisn** [comment]
@Bombardirgh lemme check them first and I will add them later. Well done!

**Comment by wisn** [comment]
@Bombardirgh Thanks for your hard work! We will add your repository to our list!
