### ISSUE TITLE
Ganesha Danu Enastika / Programmer

### ISSUE THREAD

**Issue by blinfoldking** [helloproclub/takehome#5]
https://github.com/BlinfoldKing/BlinfoldKing.github.io
https://github.com/BlinfoldKing/SupercloneProject

**Comment by wisn** [comment]
@BlinfoldKing lemme check them first and I will add them later. Well done!

**Comment by wisn** [comment]
@BlinfoldKing Thanks for your hard work! We will add your repository to our list!
